name: workflow.yml
on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
jobs:
  setup-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
      - name: Run tests
        run: pytest
      - name: Upload allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
  upload-allure-report:
    needs: setup-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download allure-results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - name: Get allure-history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate allure-report
        run: | 
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-history
      - name: Deploy report to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history

